### PR TITLE
Added SAM2 model and post-processing

### PR DESCRIPTION
**Pull request by mese79**
- Added **SAM2** `large` and `base_plus` modes
- Updated post-processing using `SAM2 base_plus` instead of `light_hq_sam`
- Updates setup `toml` and provided `envs`

The setup process might be still problematic, and it needs more testing.  
SAM2 can be installed easily using `conda`, but for `pip`, it will be installed from the git repo.  I need to find a way to publish it to `pypi` since it doesn't support github link dependency.

### CODE REVIEW

**Comment by jdeschamps** [comment]
Two ways forward:

1) We could make it a dependency without Github and then write instructions in the README to install SAM2 via conda. Would that be PyPi compatible?

2) Make SAM2 an optional dependency, detect it at run time and guard against it not being present.

**Comment by mese79** [comment]
Both solutions seem good! Also, another way is to make a SAM2 pypi package just for our installation purpose.  
There is one on pypi, but it seems it's not up to date and the maintainer is unknown.
But first I need to check why tests won't pass anymore! :(

**Comment by jdeschamps** [comment]
> Both solutions seem good! Also, another way is to make a SAM2 pypi package just for our installation purpose. There is one on pypi, but it seems it's not up to date and the maintainer is unknown. First I need to check why tests won't pass anymore! :(

I would not commit to maintain a PyPi SAM 2 package! Things change too fast.

**Comment by mese79** [comment]
I commented out the `sam-2` dependency from `pyproject.toml` since the installation of `sam-2` via pip would turn into a mess easily!  
So, I guess I need to update the `README` to emphasize the installation process using `conda` and the provided `yaml` files.

**Pull request merged**
